Analyze Crashes
ReactionMechanismGenerator/ReactionMechanismSimulator.jl pull request #174
Opened 2021-10-18 20:26 UTC by mjohnson541

This provides functionality for analyzing why a mechanism simulation crashed in terms of reactions, kinetics and thermochemistry. Also adds some functionality for analyzing collision limit violations, but only relative to H+H->H2 since sigma and epsilon often aren't available.

2021-11-30 15:24 UTC, hwpang commented on src/Debugging.jl
> +    ratio::Float64 = 0.0
From developer hour: rt is rate, ratio is attempt to scale the rate so we have a way to threshold the tolerance, which is rt/medium of rates

2021-11-30 15:35 UTC, hwpang requested changes
Mostly looks good to me! Only a couple of requests. Could you also write a jupyter notebook using these functions? It's just easier to point new users to a jupyter notebook to learn how to use new stuff

2021-12-03 17:06 UTC, mjohnson541 commented on src/Debugging.jl
> +    ratio::Float64 = 0.0
added docstrings

2021-12-03 17:06 UTC, mjohnson541 commented
I think I've made all the requested changes.

2021-12-05 02:28 UTC, hwpang approved these changes
Looks good to me! I will merge it.

2021-12-05 02:28 UTC, merged