Add volumetric inlet, revamp comments for Jacobian derivation, and debug Jacoabian for interfaces
ReactionMechanismGenerator/ReactionMechanismSimulator.jl pull request #207
Opened 2023-03-16 22:00 UTC by hwpang

2023-04-12 21:44 UTC, mjohnson541 requested changes

2023-04-15 03:09 UTC, hwpang commented on src/Interface.jl
> +        H = conddict["Hin"]
I changed Hin to be J/mol to be consistent with the Hin in Inlet, and calculate Hpervolume (J/m^3) to append to the domain.

2023-04-15 03:09 UTC, hwpang commented on src/Domain.jl
> +            @simd for i in domain.indexes[1]:domain.indexes[2]
Done

2023-04-15 03:10 UTC, hwpang commented on src/Domain.jl
> +                ddnidTdt = inter.Vin(t)*(Us[i]/V)/(N*Cvave)
Fixed

2023-04-15 03:10 UTC, hwpang commented on src/Domain.jl
> +                @inbounds @fastmath jac[domain.indexes[3],i] += inter.Vin(t)*(Hs[i]/V)/(N*Cpave) - dTdt*(dCpavedni/Cpave)
Fixed

2023-05-24 21:00 UTC, merged